# name: golang
# version: 1.21.5
common:
  file: msrvct.yaml
  path: /etc/msrvct
scripts:
  pre_script:
    - pre_script.sh
  post_script:
    - post_script.sh
variables:
  # global
  # src: /workspaces/msrvct-exec/debug/golang/1.21.5
packages:
  - name: golang
    version: 1.21.5
    documents:
      - name: go1.21.5.linux-amd64.tar.gz
        type: pkg
        path_mode: 0755
        file_mode: 0755
        sub_dir: go
      - name: golang.env
        type: env
        template: true
        path_mode: 0755
        file_mode: 0755
